apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-pv
  namespace: awx
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <your-volume-id>
    fsType: ext4
