apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: LoadBalancer
  web_extra_volume_mounts:
    - name: awx-data
      mountPath: /var/lib/awx/data
  web_extra_volumes:
    - name: awx-data
      persistentVolumeClaim:
        claimName: awx-pvc
