apiVersion: v1
kind: NetworkPolicy
metadata:
  name: allow-awx
  namespace: awx
spec:
  podSelector:
    matchLabels:
      app: awx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: awx
